services:
  api:
    container_name: social_network_api
    build:
      context: .
      dockerfile: ./api/Dockerfile.api
    ports:
      - 1337:80
    restart: unless-stopped
        
  client:
    container_name: petrol_station_client
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
    ports:
      - 80:8000
    restart: unless-stopped

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - type: bind
        source: ./postgresql_data
        target: /var/lib/postgresql/data
        read_only: false
    ports:
      - 5432:5432
    build:
      context: .
      shm_size: '4gb'

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080